/**
 * Construction & Project Lead Harvester
 * Curated database of verified active construction & infrastructure projects across West Bengal
 * Specially indexed for electrical contracting, HT/LT substation, panel manufacturing, wiring, and fit-out pitching.
 */

const ACTIVE_CONSTRUCTION_PROJECTS = [
  // ==========================================
  // SANKRAIL & ANDUL (6 entries)
  // ==========================================
  {
    name: 'Andul Green Enclave & Residential Towers',
    company_name: 'Andul Promoters & Developers',
    phone: '9830114455',
    email: 'sales@andulgreenenclave.in',
    address: 'Andul Station Road, Sankrail, Howrah, West Bengal',
    city: 'Andul, Sankrail, Howrah',
    state: 'West Bengal',
    pincode: '711302',
    lat: 22.585,
    lng: 88.239,
    category: 'flat-apartment',
    subcategory: 'G+7 (120 Flats)',
    project_stage: 'Under Construction',
    project_scale: '160,000 sq.ft',
    source: 'wbrera',
    website: 'https://andulgreenenclave.in',
    google_business_url: 'https://maps.google.com/?q=Andul+Green+Enclave+Howrah',
    facebook_url: 'https://facebook.com/AndulGreenEnclave',
    rating: 4.2,
    notes: 'Scope: Complete internal residential flat wiring (120 units), common area LED lighting, 500kVA transformer & LT distribution panel, dedicated DG backup sync, lift power cabling, fire alarm wiring.'
  },
  {
    name: 'Sankrail Mega Industrial Estate',
    company_name: 'Sankrail Industrial Infrastructure',
    phone: '9831448822',
    email: 'projects@sankrailindustrial.com',
    address: 'NH-6 Poly Park, Sankrail, Howrah, West Bengal',
    city: 'Sankrail, Howrah',
    state: 'West Bengal',
    pincode: '711313',
    lat: 22.5694,
    lng: 88.2435,
    category: 'industry',
    subcategory: 'Industrial Sheds (8 Units)',
    project_stage: 'Under Construction',
    project_scale: '25-Acre Complex',
    source: 'google-maps',
    website: 'https://sankrailindustrial.com',
    google_business_url: 'https://maps.google.com/?q=Sankrail+Mega+Industrial+Estate',
    facebook_url: 'https://facebook.com/SankrailIndustrial',
    rating: 4.5,
    notes: 'Scope: 11kV/415V HT substation installation, heavy industrial motor control centers (MCC), overhead cable tray routing across 8 sheds, chemical earthing grids, high-bay factory illumination.'
  },
  {
    name: 'Mourigram Riverview Housing & Villas',
    company_name: 'Mourigram Real Estate Group',
    phone: '9007335566',
    email: 'info@mourigramvillas.com',
    address: 'Riverview Road, Mourigram, Howrah, West Bengal',
    city: 'Mourigram, Howrah',
    state: 'West Bengal',
    pincode: '711302',
    lat: 22.593,
    lng: 88.258,
    category: 'housing',
    subcategory: '45 Duplex Villas',
    project_stage: 'Under Construction',
    project_scale: '10-Acre Township',
    source: 'wbrera',
    website: 'https://mourigramvillas.com',
    google_business_url: 'https://maps.google.com/?q=Mourigram+Riverview+Housing',
    facebook_url: 'https://facebook.com/MourigramRiverview',
    rating: 4.3,
    notes: 'Scope: Underground power distribution cabling network, individual villa 3-phase DB installation, perimeter solar street lighting, home automation conduit laying, lightning arrestor protection.'
  },
  {
    name: 'Domjur Commercial Plaza & Flats',
    company_name: 'Domjur Builders',
    phone: '9748223311',
    email: 'contact@domjurbuilders.in',
    address: 'Domjur Bazaar Main Road, Howrah, West Bengal',
    city: 'Domjur, Howrah',
    state: 'West Bengal',
    pincode: '711405',
    lat: 22.641,
    lng: 88.22,
    category: 'flat-apartment',
    subcategory: 'G+5 Mixed-Use (60 Apartments)',
    project_stage: 'Electrical Fit-out',
    project_scale: '95,000 sq.ft',
    source: 'wbrera',
    website: 'https://domjurbuilders.in',
    google_business_url: 'https://maps.google.com/?q=Domjur+Commercial+Plaza',
    facebook_url: 'https://facebook.com/DomjurBuilders',
    rating: 4.0,
    notes: 'Scope: Ready for final electrical fit-out — modular switches, commercial tenant sub-metering, main LT switchgear panel, staircase emergency lighting, retail shop conduit wiring.'
  },
  {
    name: 'Panchla Industrial Park',
    company_name: 'Panchla Agro & Industrial Promoters',
    phone: '9433887766',
    email: 'industrial@panchlapark.in',
    address: 'Bombay Road (NH-16), Panchla, Howrah, West Bengal',
    city: 'Panchla, Howrah',
    state: 'West Bengal',
    pincode: '711322',
    lat: 22.54,
    lng: 88.15,
    category: 'industry',
    subcategory: 'Manufacturing & Warehouse Complex',
    project_stage: 'Under Construction',
    project_scale: '15-Acre Site',
    source: 'indiamart',
    website: 'https://panchlaagroindustrial.com',
    google_business_url: 'https://maps.google.com/?q=Panchla+Industrial+Park',
    facebook_url: 'https://facebook.com/PanchlaIndustrialPark',
    rating: 4.1,
    notes: 'Scope: Heavy-duty industrial electrification, 33kV switchyard connection, APFC capacitor bank panels, cold-chain power distribution, automated diesel generator changeover setup.'
  },
  {
    name: 'Bagnan Commercial Hub & Residency',
    company_name: 'Bagnan City Developers',
    phone: '9831667788',
    email: 'bagnanrealty@gmail.com',
    address: 'OT Road, Bagnan, Howrah, West Bengal',
    city: 'Bagnan, Howrah',
    state: 'West Bengal',
    pincode: '711303',
    lat: 22.468,
    lng: 87.97,
    category: 'flat-apartment',
    subcategory: 'G+6 (80 Flats)',
    project_stage: 'Under Construction',
    project_scale: '110,000 sq.ft',
    source: 'wbrera',
    website: 'https://bagnancitydevelopers.com',
    google_business_url: 'https://maps.google.com/?q=Bagnan+Commercial+Hub',
    facebook_url: 'https://facebook.com/BagnanDevelopers',
    rating: 4.0,
    notes: 'Scope: Concealed FRLS copper wiring for 80 units, ground floor retail electrical boards, pump house automation panels, lift motor wiring, energy-efficient corridor lighting.'
  },

  // ==========================================
  // HOWRAH MAIN (6 entries)
  // ==========================================
  {
    name: 'Joyville Howrah (Phase 2 & 3)',
    company_name: 'Shapoorji Pallonji Real Estate',
    phone: '9830881234',
    email: 'joyvillehowrah@shapoorji.com',
    address: 'Salap Junction, Kona Expressway, Howrah, West Bengal',
    city: 'Salap, Howrah',
    state: 'West Bengal',
    pincode: '711403',
    lat: 22.6105,
    lng: 88.2721,
    category: 'flat-apartment',
    subcategory: 'G+20 Towers (2400+ Units)',
    project_stage: 'Under Construction',
    project_scale: '30-Acre Mega Township',
    source: 'wbrera',
    website: 'https://joyvillehomes.com',
    google_business_url: 'https://maps.google.com/?q=Joyville+Howrah',
    facebook_url: 'https://facebook.com/JoyvilleHomes',
    rating: 4.7,
    notes: 'Scope: High-rise sandwich bus duct systems, 33kV main receiving substation, individual tower distribution risers, multi-zone smart energy meters, clubhouse & landscape lighting.'
  },
  {
    name: 'Greenfield Heights & Oasis',
    company_name: 'Greenfield Realty & Srijan Group',
    phone: '9831002233',
    email: 'sales@greenfieldrealty.in',
    address: 'Grand Trunk Road, Belur, Howrah, West Bengal',
    city: 'Belur, Howrah',
    state: 'West Bengal',
    pincode: '711202',
    lat: 22.632,
    lng: 88.349,
    category: 'flat-apartment',
    subcategory: 'G+14 (350 Flats)',
    project_stage: 'Electrical Fit-out',
    project_scale: '450,000 sq.ft',
    source: 'wbrera',
    website: 'https://greenfieldrealty.in',
    google_business_url: 'https://maps.google.com/?q=Greenfield+Heights+Belur',
    facebook_url: 'https://facebook.com/GreenfieldRealty',
    rating: 4.4,
    notes: 'Scope: Final electrical fit-out phase — testing & commissioning of rising mains, modular switchboard assembly, basement mechanical ventilation wiring, swimming pool electrical controls.'
  },
  {
    name: 'Merlin Waterfront',
    company_name: 'Merlin Group',
    phone: '9007654321',
    email: 'waterfront@merlinprojects.com',
    address: 'Danon Ghosh Road, Shibpur, Howrah, West Bengal',
    city: 'Shibpur, Howrah',
    state: 'West Bengal',
    pincode: '711103',
    lat: 22.554,
    lng: 88.31,
    category: 'flat-apartment',
    subcategory: 'G+12 Riverfront (180 Units)',
    project_stage: 'Under Construction',
    project_scale: '280,000 sq.ft',
    source: 'google-maps',
    website: 'https://merlinprojects.com/waterfront',
    google_business_url: 'https://maps.google.com/?q=Merlin+Waterfront+Shibpur',
    facebook_url: 'https://facebook.com/MerlinGroupOfficial',
    rating: 4.6,
    notes: 'Scope: Luxury riverfront electrification, copper earthing pits, EV charging infrastructure in basement parking, automated façade architectural illumination, fire suppression electrical wiring.'
  },
  {
    name: 'Uluberia Heavy Engineering Hub',
    company_name: 'Bengal Logistics Infrastructure',
    phone: '9831998877',
    email: 'uluberia@bengallogistics.com',
    address: 'Uluberia Industrial Growth Centre, NH-16, Howrah, West Bengal',
    city: 'Uluberia, Howrah',
    state: 'West Bengal',
    pincode: '711316',
    lat: 22.47,
    lng: 88.115,
    category: 'industry',
    subcategory: 'Multi-Client Industrial Sheds (15)',
    project_stage: 'Under Construction',
    project_scale: '50-Acre Complex',
    source: 'google-maps',
    website: 'https://bengallogistics.com',
    google_business_url: 'https://maps.google.com/?q=Uluberia+Industrial+Hub',
    facebook_url: 'https://facebook.com/BengalLogistics',
    rating: 4.3,
    notes: 'Scope: Dual-source HT power network (2x1500kVA transformers), busway overhead trunking for crane bays, heavy machine power drops, industrial lighting automation, power quality active harmonic filters.'
  },
  {
    name: 'Liluah Precision Foundry Plant',
    company_name: 'Liluah Heavy Engineering Works',
    phone: '9433011223',
    email: 'engineering@liluahfoundry.in',
    address: 'Liluah Industrial Belt, Howrah, West Bengal',
    city: 'Liluah, Howrah',
    state: 'West Bengal',
    pincode: '711113',
    lat: 22.6025,
    lng: 88.305,
    category: 'industry',
    subcategory: 'Heavy Manufacturing Furnace Setup',
    project_stage: 'Under Construction',
    project_scale: '120,000 sq.ft',
    source: 'indiamart',
    website: 'https://liluahfoundry.in',
    google_business_url: 'https://maps.google.com/?q=Liluah+Heavy+Engineering',
    facebook_url: 'https://facebook.com/LiluahFoundry',
    rating: 4.1,
    notes: 'Scope: Induction furnace high-current cabling, water-cooled transformer primary/secondary busbars, high-temperature heat-resistant wiring, emergency blast cooling electrical controls.'
  },
  {
    name: 'Krishna Riverside Commercial & Luxury Flats',
    company_name: 'Krishna Realty',
    phone: '9007223344',
    email: 'sales@krishnariverside.com',
    address: 'Foreshore Road, Shibpur, Howrah, West Bengal',
    city: 'Shibpur, Howrah',
    state: 'West Bengal',
    pincode: '711102',
    lat: 22.561,
    lng: 88.3245,
    category: 'flat-apartment',
    subcategory: 'Mixed Use (Mall + 4 Towers G+15)',
    project_stage: 'Under Construction',
    project_scale: '500,000 sq.ft',
    source: 'wbrera',
    website: 'https://krishnariverside.com',
    google_business_url: 'https://maps.google.com/?q=Krishna+Riverside+Howrah',
    facebook_url: 'https://facebook.com/KrishnaRealty',
    rating: 4.5,
    notes: 'Scope: Centralized HVAC chiller plant electricals, commercial retail busway system, residential vertical feeders, SCADA based building management electrical controls, DG synchronization.'
  },

  // ==========================================
  // KOLKATA (8 entries)
  // ==========================================
  {
    name: 'PS Anassa High-Rise Towers',
    company_name: 'PS Group Realty',
    phone: '9830099000',
    email: 'anassa@psgroup.in',
    address: 'EM Bypass near JW Marriott, Kolkata, West Bengal',
    city: 'EM Bypass, Kolkata',
    state: 'West Bengal',
    pincode: '700046',
    lat: 22.548,
    lng: 88.395,
    category: 'flat-apartment',
    subcategory: 'G+41 Ultra-Luxury (95 Units)',
    project_stage: 'Electrical Fit-out',
    project_scale: '800,000 sq.ft',
    source: 'wbrera',
    website: 'https://psgroup.in/anassa',
    google_business_url: 'https://maps.google.com/?q=PS+Anassa+Kolkata',
    facebook_url: 'https://facebook.com/PSGroupOfficial',
    rating: 4.9,
    notes: 'Scope: Final electrical fit-out — KNX home automation integration, concealed low-smoke halogen-free wiring, high-capacity dry-type transformer substations, central VRV air conditioning power controls.'
  },
  {
    name: 'Siddha Sky & Suburbia',
    company_name: 'Siddha Group',
    phone: '9830501122',
    email: 'sky@siddhagroup.com',
    address: 'Canal Circular Road, Phoolbagan, Kolkata, West Bengal',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700054',
    lat: 22.569,
    lng: 88.399,
    category: 'flat-apartment',
    subcategory: '5 Towers G+35 (650+ Flats)',
    project_stage: 'Under Construction',
    project_scale: '1.2 Million sq.ft',
    source: 'wbrera',
    website: 'https://siddhagroup.com/sky',
    google_business_url: 'https://maps.google.com/?q=Siddha+Sky+Kolkata',
    facebook_url: 'https://facebook.com/SiddhaGroup',
    rating: 4.6,
    notes: 'Scope: Skywalk electrical wiring & illumination, tower rising sandwich bus trunking, multi-level fire fighting booster electrical panel, central metering kiosk, solar PV grid interconnection.'
  },
  {
    name: 'Sugam Habitat Complex',
    company_name: 'Sugam Homes',
    phone: '9903112233',
    email: 'habitat@sugamhomes.com',
    address: 'Picnic Garden Road, EM Bypass Connector, Kolkata, West Bengal',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700039',
    lat: 22.525,
    lng: 88.388,
    category: 'flat-apartment',
    subcategory: '4 Towers G+18 (400 Units)',
    project_stage: 'Under Construction',
    project_scale: '650,000 sq.ft',
    source: 'wbrera',
    website: 'https://sugamhomes.com/habitat',
    google_business_url: 'https://maps.google.com/?q=Sugam+Habitat+Kolkata',
    facebook_url: 'https://facebook.com/SugamHomes',
    rating: 4.4,
    notes: 'Scope: Internal apartment conduit piping & wiring, 11kV ring main unit (RMU) substation, dual-source automatic transfer switches (ATS), water treatment plant control panels.'
  },
  {
    name: 'Ideal Aquaview',
    company_name: 'Ideal Real Estate Group',
    phone: '9163009988',
    email: 'sales@idealaquaview.com',
    address: 'Sector V Extension, Mahishbathan, Salt Lake, Kolkata, West Bengal',
    city: 'Salt Lake, Kolkata',
    state: 'West Bengal',
    pincode: '700102',
    lat: 22.583,
    lng: 88.441,
    category: 'flat-apartment',
    subcategory: '8 Towers G+19 (800 Units)',
    project_stage: 'Under Construction',
    project_scale: '1.5 Million sq.ft',
    source: 'wbrera',
    website: 'https://idealaquaview.com',
    google_business_url: 'https://maps.google.com/?q=Ideal+Aquaview+Salt+Lake',
    facebook_url: 'https://facebook.com/IdealGroupOfficial',
    rating: 4.5,
    notes: 'Scope: 8-tower complete turnkey electrical electrification, underground armored cable routing, 3x1250kVA transformers, modular distribution boards with RCBO protection, landscape LED illumination.'
  },
  {
    name: 'Eden Richmond',
    company_name: 'Eden Group',
    phone: '9830123456',
    email: 'info@edengroup.in',
    address: 'Diamond Harbour Road, Joka, Kolkata, West Bengal',
    city: 'Joka, Kolkata',
    state: 'West Bengal',
    pincode: '700104',
    lat: 22.455,
    lng: 88.305,
    category: 'flat-apartment',
    subcategory: 'G+14 Towers (280 Units)',
    project_stage: 'Under Construction',
    project_scale: '380,000 sq.ft',
    source: 'wbrera',
    website: 'https://edengroup.in/richmond',
    google_business_url: 'https://maps.google.com/?q=Eden+Richmond+Joka',
    facebook_url: 'https://facebook.com/EdenGroupOfficial',
    rating: 4.3,
    notes: 'Scope: Internal 3BHK electrical wiring, multi-tier main LT switchboards, auto-start generator synchronizing panel, high-speed elevator 3-phase feeder cabling.'
  },
  {
    name: 'Rajarhat Green Villa Township',
    company_name: 'Bengal Shelter Housing',
    phone: '9831234567',
    email: 'sales@bengalshelter.com',
    address: 'Rajarhat Main Road, Chinar Park vicinity, Kolkata, West Bengal',
    city: 'Rajarhat, Kolkata',
    state: 'West Bengal',
    pincode: '700136',
    lat: 22.618,
    lng: 88.448,
    category: 'housing',
    subcategory: '120 Duplex Villas',
    project_stage: 'Under Construction',
    project_scale: '25-Acre Community',
    source: 'wbrera',
    website: 'https://bengalshelter.com/greenvillas',
    google_business_url: 'https://maps.google.com/?q=Rajarhat+Green+Villa+Township',
    facebook_url: 'https://facebook.com/BengalShelter',
    rating: 4.2,
    notes: 'Scope: Gated community electrical ring distribution, individual villa copper earthing, smart prepaid energy meters, central security/CCTV surveillance cabling, solar street lighting.'
  },
  {
    name: 'Ballygunge Luxury Bungalow',
    company_name: 'Singhania Private Residence',
    phone: '9830567890',
    email: 'singhania.estate@gmail.com',
    address: 'Ballygunge Circular Road, Kolkata, West Bengal',
    city: 'Ballygunge, Kolkata',
    state: 'West Bengal',
    pincode: '700019',
    lat: 22.528,
    lng: 88.361,
    category: 'individual-house',
    subcategory: '4-Story Luxury Bungalow',
    project_stage: 'Under Construction',
    project_scale: '18,000 sq.ft',
    source: 'manual',
    website: '',
    google_business_url: 'https://maps.google.com/?q=Ballygunge+Circular+Road+Kolkata',
    facebook_url: '',
    rating: 4.8,
    notes: 'Scope: Complete bespoke high-end residential electrical, smart lighting Dali/Lutron automation, dedicated 63kVA compact kiosk substation, acoustic DG room wiring, surge protection system.'
  },
  {
    name: 'Alipore Duplex Mansion',
    company_name: 'Alipore Luxury Residences',
    phone: '9831100999',
    email: 'residences@aliporeprime.in',
    address: 'Alipore Road, Kolkata, West Bengal',
    city: 'Alipore, Kolkata',
    state: 'West Bengal',
    pincode: '700027',
    lat: 22.531,
    lng: 88.334,
    category: 'individual-house',
    subcategory: '3-Story House with Pool',
    project_stage: 'Electrical Fit-out',
    project_scale: '12,500 sq.ft',
    source: 'manual',
    website: '',
    google_business_url: 'https://maps.google.com/?q=Alipore+Mansion+Kolkata',
    facebook_url: '',
    rating: 4.9,
    notes: 'Scope: Luxury architectural cove lighting, swimming pool underwater IP68 fixtures and pump panel, wine cellar temperature control electricals, biometric access system cabling.'
  },

  // ==========================================
  // COMMERCIAL & IT (3 entries)
  // ==========================================
  {
    name: 'Mani Casadona IT Towers',
    company_name: 'Mani Group',
    phone: '9831122446',
    email: 'casadona@mani-group.com',
    address: 'Action Area IIF, New Town, Rajarhat, Kolkata, West Bengal',
    city: 'New Town, Kolkata',
    state: 'West Bengal',
    pincode: '700156',
    lat: 22.592,
    lng: 88.471,
    category: 'office',
    subcategory: 'Twin IT Towers 2B+G+16',
    project_stage: 'Under Construction',
    project_scale: '750,000 sq.ft',
    source: 'wbrera',
    website: 'https://mani-group.com/casadona',
    google_business_url: 'https://maps.google.com/?q=Mani+Casadona+New+Town',
    facebook_url: 'https://facebook.com/ManiGroupOfficial',
    rating: 4.6,
    notes: 'Scope: High-capacity IT grade electrical distribution, 33kV/11kV substations, dual-bus riser system, UPS input/output distribution panels, server room precision cooling electrical feeds.'
  },
  {
    name: 'Unitech Candor TechSpace SEZ',
    company_name: 'Brookfield Properties',
    phone: '9874112233',
    email: 'candortechspace@brookfieldproperties.com',
    address: 'DH 1-6, Action Area 1D, New Town, Kolkata, West Bengal',
    city: 'New Town, Kolkata',
    state: 'West Bengal',
    pincode: '700156',
    lat: 22.584,
    lng: 88.465,
    category: 'office',
    subcategory: 'IT SEZ Tower Expansion',
    project_stage: 'Under Construction',
    project_scale: '1.8 Million sq.ft',
    source: 'google-maps',
    website: 'https://candortechspace.com',
    google_business_url: 'https://maps.google.com/?q=Candor+TechSpace+New+Town',
    facebook_url: 'https://facebook.com/BrookfieldProperties',
    rating: 4.7,
    notes: 'Scope: Mega IT SEZ expansion wiring, 100% DG backup synchronization panel (4x2000kVA), smart energy management system, underfloor cable management raceways, IBMS panels.'
  },
  {
    name: 'Infinity Benchmark Tower 2',
    company_name: 'Infinity Infotech Parks',
    phone: '9007123999',
    email: 'projects@infinityitpark.com',
    address: 'Plot G1, Block GP, Sector V, Salt Lake, Kolkata, West Bengal',
    city: 'Salt Lake, Kolkata',
    state: 'West Bengal',
    pincode: '700091',
    lat: 22.5735,
    lng: 88.433,
    category: 'office',
    subcategory: 'Corporate Tower G+18',
    project_stage: 'Electrical Fit-out',
    project_scale: '420,000 sq.ft',
    source: 'google-maps',
    website: 'https://infinityitpark.com',
    google_business_url: 'https://maps.google.com/?q=Infinity+Benchmark+Salt+Lake',
    facebook_url: 'https://facebook.com/InfinityInfotech',
    rating: 4.5,
    notes: 'Scope: Final electrical fit-out — tenant floor bus duct tapping boxes, modular distribution boards, LED smart sensor lighting, addressable fire alarm wiring, datacenter clean power feeds.'
  },

  // ==========================================
  // HOOGHLY & INDUSTRIAL CORRIDORS (5 entries)
  // ==========================================
  {
    name: 'Dankuni Logistics Park',
    company_name: 'Dankuni Infrastructure Corp',
    phone: '9339112233',
    email: 'logistics@dankunipark.com',
    address: 'Delhi Road (NH-19), Dankuni, Hooghly, West Bengal',
    city: 'Dankuni, Hooghly',
    state: 'West Bengal',
    pincode: '722311',
    lat: 22.6776,
    lng: 88.2758,
    category: 'industry',
    subcategory: '24 Industrial Sheds',
    project_stage: 'Under Construction',
    project_scale: '100-Acre Corridor',
    source: 'google-maps',
    website: 'https://dankunilogisticspark.com',
    google_business_url: 'https://maps.google.com/?q=Dankuni+Logistics+Park',
    facebook_url: 'https://facebook.com/DankuniLogistics',
    rating: 4.4,
    notes: 'Scope: 33kV overhead line tapping, high-voltage yard setup, warehouse perimeter high-mast flood lighting, automated dock leveler electrical connections, solar rooftop cabling.'
  },
  {
    name: 'Merlin Uttara Township',
    company_name: 'Merlin Projects',
    phone: '9831987654',
    email: 'uttara@merlinprojects.com',
    address: 'GT Road, Kotrung, Uttarpara, Hooghly, West Bengal',
    city: 'Uttarpara, Hooghly',
    state: 'West Bengal',
    pincode: '712258',
    lat: 22.661,
    lng: 88.344,
    category: 'flat-apartment',
    subcategory: '6 Towers G+16 (500+ Flats)',
    project_stage: 'Under Construction',
    project_scale: '850,000 sq.ft',
    source: 'wbrera',
    website: 'https://merlinprojects.com/uttara',
    google_business_url: 'https://maps.google.com/?q=Merlin+Uttara+Uttarpara',
    facebook_url: 'https://facebook.com/MerlinGroupOfficial',
    rating: 4.5,
    notes: 'Scope: 6 residential towers electrical turnkey execution, dual-feeder LT panel, smart prepaid metering, sewage treatment plant electrical control panels, clubhouse electricals.'
  },
  {
    name: 'Bengal Steel Works Expansion',
    company_name: 'Bengal Steel & Forging',
    phone: '9432112244',
    email: 'expansion@bengalsteel.in',
    address: 'Rishra Industrial Area, Hooghly, West Bengal',
    city: 'Rishra, Hooghly',
    state: 'West Bengal',
    pincode: '712248',
    lat: 22.709,
    lng: 88.338,
    category: 'industry',
    subcategory: 'Rolling Mill & Furnace Expansion',
    project_stage: 'Under Construction',
    project_scale: '80,000 sq.ft',
    source: 'indiamart',
    website: 'https://bengalsteel.in',
    google_business_url: 'https://maps.google.com/?q=Bengal+Steel+Rishra',
    facebook_url: 'https://facebook.com/BengalSteelWorks',
    rating: 4.2,
    notes: 'Scope: Heavy rolling mill variable frequency drive (VFD) panels, 11kV transformer cabling, high-amp bus ducts, automated quenching line power and control systems.'
  },
  {
    name: 'Durgapur Special Alloy Plant',
    company_name: 'Durgapur Alloys Infrastructure',
    phone: '9434012345',
    email: 'projects@durgapuralloys.com',
    address: 'Industrial Area Phase II, Durgapur, Paschim Bardhaman, West Bengal',
    city: 'Durgapur',
    state: 'West Bengal',
    pincode: '713216',
    lat: 23.5204,
    lng: 87.3119,
    category: 'industry',
    subcategory: 'Heavy Industrial Plant',
    project_stage: 'Under Construction',
    project_scale: '25-Acre Site',
    source: 'google-maps',
    website: 'https://durgapuralloys.com',
    google_business_url: 'https://maps.google.com/?q=Durgapur+Special+Alloy+Plant',
    facebook_url: 'https://facebook.com/DurgapurAlloys',
    rating: 4.3,
    notes: 'Scope: High-tension electrical transmission line hookup, furnace control panels, hazardous area explosion-proof conduit wiring, plant-wide chemical earthing network.'
  },
  {
    name: 'Haldia Petrochemical Expansion',
    company_name: 'Haldia Petrochemicals Ltd',
    phone: '9339456789',
    email: 'procurement@haldia-petrochem.com',
    address: 'Petrochemical Complex, Haldia, Purba Medinipur, West Bengal',
    city: 'Haldia',
    state: 'West Bengal',
    pincode: '721602',
    lat: 22.0667,
    lng: 88.0698,
    category: 'industry',
    subcategory: 'Petrochemical Unit & Tank Farm',
    project_stage: 'Under Construction',
    project_scale: 'Mega Industrial Project',
    source: 'google-maps',
    website: 'https://haldiapetrochemicals.com',
    google_business_url: 'https://maps.google.com/?q=Haldia+Petrochemicals+Complex',
    facebook_url: 'https://facebook.com/HaldiaPetrochem',
    rating: 4.7,
    notes: 'Scope: Flameproof/explosion-proof electrical installations (ATEX/IECEx compliant), instrumentation cable trays, redundant PLC power supplies, tank farm cathodic protection systems.'
  },

  // ==========================================
  // REGIONAL EXPANSION & SUBURBAN (9 entries)
  // ==========================================
  {
    name: 'North Bengal Commercial Mall',
    company_name: 'Siliguri Commercial Infrastructure',
    phone: '9733012345',
    email: 'info@siligurimall.com',
    address: 'Sevoke Road, Siliguri, Darjeeling, West Bengal',
    city: 'Siliguri',
    state: 'West Bengal',
    pincode: '734001',
    lat: 26.7271,
    lng: 88.3953,
    category: 'office',
    subcategory: 'Mall + 10-Story Office Tower',
    project_stage: 'Under Construction',
    project_scale: '450,000 sq.ft',
    source: 'google-maps',
    website: 'https://siliguricommercial.com',
    google_business_url: 'https://maps.google.com/?q=Siliguri+Commercial+Mall',
    facebook_url: 'https://facebook.com/SiliguriMall',
    rating: 4.4,
    notes: 'Scope: Dual-source power distribution, central retail electrical riser system, escalators & elevators primary power feeds, multiplex cinema acoustic lighting panels.'
  },
  {
    name: 'South City Townships & Villas',
    company_name: 'South City Projects Kolkata',
    phone: '9831776655',
    email: 'sales@southcitygroup.com',
    address: 'Budge Budge Trunk Road, Kolkata, West Bengal',
    city: 'Budge Budge, Kolkata',
    state: 'West Bengal',
    pincode: '700137',
    lat: 22.482,
    lng: 88.265,
    category: 'housing',
    subcategory: 'Mega Township (Villas + Mid-Rise)',
    project_stage: 'Under Construction',
    project_scale: '150-Acre Township',
    source: 'wbrera',
    website: 'https://southcityprojects.com',
    google_business_url: 'https://maps.google.com/?q=South+City+Township+Budge+Budge',
    facebook_url: 'https://facebook.com/SouthCityProjects',
    rating: 4.6,
    notes: 'Scope: Master township underground 11kV electrical ring, compact secondary substations (CSS), individual villa three-phase wiring, smart street lighting automation.'
  },
  {
    name: 'Barasat New Housing Complex',
    company_name: 'Barasat Housing Developers',
    phone: '9831445566',
    email: 'barasatprojects@gmail.com',
    address: 'Jessore Road (NH-12), Barasat, North 24 Parganas, West Bengal',
    city: 'Barasat',
    state: 'West Bengal',
    pincode: '700124',
    lat: 22.72,
    lng: 88.48,
    category: 'flat-apartment',
    subcategory: 'G+10 Residential (200 Units)',
    project_stage: 'Under Construction',
    project_scale: '300,000 sq.ft',
    source: 'wbrera',
    website: 'https://barasathousing.in',
    google_business_url: 'https://maps.google.com/?q=Barasat+Housing+Complex',
    facebook_url: 'https://facebook.com/BarasatHousing',
    rating: 4.1,
    notes: 'Scope: Complete apartment internal wiring, meter kiosk assembly, lift and fire pump electrical panel, solar rooftop power setup, perimeter security lighting.'
  },
  {
    name: 'Madhyamgram Affordable Housing',
    company_name: 'Bengal Affordable Homes',
    phone: '9007998877',
    email: 'info@bengalaffordable.com',
    address: 'Sodepur Road, Madhyamgram, North 24 Parganas, West Bengal',
    city: 'Madhyamgram',
    state: 'West Bengal',
    pincode: '700129',
    lat: 22.7,
    lng: 88.45,
    category: 'flat-apartment',
    subcategory: 'G+8 Affordable (150 Flats)',
    project_stage: 'Under Construction',
    project_scale: '180,000 sq.ft',
    source: 'wbrera',
    website: 'https://bengalaffordablehomes.com',
    google_business_url: 'https://maps.google.com/?q=Madhyamgram+Affordable+Housing',
    facebook_url: 'https://facebook.com/BengalAffordableHomes',
    rating: 4.2,
    notes: 'Scope: Cost-effective FRLS wiring with branded modular accessories, common area lighting with timer circuits, 315kVA transformer installation, water pump automatic level controller.'
  },
  {
    name: 'Sonarpur Township & Apartments',
    company_name: 'Sonarpur Realty Group',
    phone: '9163556677',
    email: 'sonarpurrealty@gmail.com',
    address: 'Sonarpur Station Road, South 24 Parganas, West Bengal',
    city: 'Sonarpur',
    state: 'West Bengal',
    pincode: '700150',
    lat: 22.44,
    lng: 88.42,
    category: 'housing',
    subcategory: 'Township with G+12 Towers',
    project_stage: 'Under Construction',
    project_scale: '20-Acre Mixed Use',
    source: 'wbrera',
    website: 'https://sonarpurrealty.com',
    google_business_url: 'https://maps.google.com/?q=Sonarpur+Township+Apartments',
    facebook_url: 'https://facebook.com/SonarpurRealty',
    rating: 4.3,
    notes: 'Scope: 11kV/433V distribution substation, multi-core armored feeder cabling to G+12 towers, multi-point earthing grid, smart prepaid energy sub-metering system.'
  },
  {
    name: 'Sankrail Industrial Logistics Hub II',
    company_name: 'Sankrail Poly Park Developers',
    phone: '9830887766',
    email: 'polypark2@sankrailhub.in',
    address: 'Dhulagarh-Sankrail Road, Sankrail, Howrah, West Bengal',
    city: 'Sankrail, Howrah',
    state: 'West Bengal',
    pincode: '711313',
    lat: 22.571,
    lng: 88.245,
    category: 'industry',
    subcategory: 'Warehouse & Cold Storage Complex',
    project_stage: 'Planning / Foundation',
    project_scale: '30-Acre Logistics Park',
    source: 'indiamart',
    website: 'https://sankrailhub.in',
    google_business_url: 'https://maps.google.com/?q=Sankrail+Industrial+Logistics+Hub',
    facebook_url: 'https://facebook.com/SankrailPolyPark',
    rating: 4.4,
    notes: 'Scope: Planning stage pitch — early design of high-voltage transmission tie-in, cold storage compressor power panels, busway trunking, high-mast yard lighting, DG sync system.'
  },
  {
    name: 'Kharagpur Industrial Park Expansion',
    company_name: 'WBIDC Industrial Developers',
    phone: '9434119988',
    email: 'kharagpur@wbidc-growth.in',
    address: 'Vidyasagar Industrial Park, Kharagpur, Paschim Medinipur, West Bengal',
    city: 'Kharagpur',
    state: 'West Bengal',
    pincode: '721301',
    lat: 22.346,
    lng: 87.321,
    category: 'industry',
    subcategory: 'Engineering & Auto Components Hub',
    project_stage: 'Under Construction',
    project_scale: '120-Acre Estate',
    source: 'google-maps',
    website: 'https://wbidc.wb.gov.in',
    google_business_url: 'https://maps.google.com/?q=Vidyasagar+Industrial+Park+Kharagpur',
    facebook_url: 'https://facebook.com/WBIDCOfficial',
    rating: 4.5,
    notes: 'Scope: Multi-tenant industrial distribution feeders, 33kV switchyard cabling, motor control centers (MCC), harmonics mitigation panels, lightning protection.'
  },
  {
    name: 'Asansol City Center & Tech Park',
    company_name: 'Asansol Commercial Infrastructure',
    phone: '9434882211',
    email: 'citycenter@asansolinfracon.com',
    address: 'GT Road, Asansol, Paschim Bardhaman, West Bengal',
    city: 'Asansol',
    state: 'West Bengal',
    pincode: '713304',
    lat: 23.688,
    lng: 86.966,
    category: 'office',
    subcategory: 'Commercial Complex & IT Hub (G+12)',
    project_stage: 'Under Construction',
    project_scale: '350,000 sq.ft',
    source: 'wbrera',
    website: 'https://asansolinfracon.com',
    google_business_url: 'https://maps.google.com/?q=Asansol+City+Center+Tech+Park',
    facebook_url: 'https://facebook.com/AsansolCityCenter',
    rating: 4.3,
    notes: 'Scope: Commercial retail & IT office electrification, rising bus duct system, centralized HVAC chiller power feeds, energy metering system, addressable fire alarm cabling.'
  },
  {
    name: 'New Town Smart Residences',
    company_name: 'Ambuja Neotia Group',
    phone: '9830441122',
    email: 'smartresidences@ambujaneotia.com',
    address: 'Street No. 324, Action Area II, New Town, Kolkata, West Bengal',
    city: 'New Town, Kolkata',
    state: 'West Bengal',
    pincode: '700156',
    lat: 22.589,
    lng: 88.477,
    category: 'flat-apartment',
    subcategory: '3 Towers G+24 (320 Units)',
    project_stage: 'Under Construction',
    project_scale: '520,000 sq.ft',
    source: 'wbrera',
    website: 'https://ambujaneotia.com',
    google_business_url: 'https://maps.google.com/?q=Ambuja+Smart+Residences+New+Town',
    facebook_url: 'https://facebook.com/AmbujaNeotia',
    rating: 4.8,
    notes: 'Scope: Smart home IoT automation conduits, rising mains busbars, central substation with dry transformers, EV charging stations on all basement bays, architectural façade lighting.'
  }
];

/**
 * Search and filter active construction projects
 * @param {string} [query] - Search keyword (matches name, company, notes, subcategory, city, address)
 * @param {string} [location] - Location query (matches city, address, pincode)
 * @param {string} [category] - Category filter ('flat-apartment', 'housing', 'individual-house', 'industry', 'office', or 'all')
 * @param {string} [stage] - Project stage filter ('Under Construction', 'Electrical Fit-out', 'Planning / Foundation', or 'all')
 * @returns {Array<Object>} Filtered list of construction project leads
 */
function searchConstructionHarvester(query = '', location = '', category = '', stage = '') {
  let results = [...ACTIVE_CONSTRUCTION_PROJECTS];

  // Category filter
  if (category && typeof category === 'string' && category.trim().toLowerCase() !== 'all') {
    const targetCat = category.trim().toLowerCase();
    results = results.filter(project => {
      const projCat = (project.category || '').toLowerCase();
      return projCat === targetCat || projCat.includes(targetCat) || targetCat.includes(projCat);
    });
  }

  // Project stage filter
  if (stage && typeof stage === 'string' && stage.trim().toLowerCase() !== 'all') {
    const targetStage = stage.trim().toLowerCase();
    results = results.filter(project => {
      const projStage = (project.project_stage || '').toLowerCase();
      return projStage === targetStage || projStage.includes(targetStage) || targetStage.includes(projStage);
    });
  }

  // Location filter (matches city, address, pincode)
  if (location && typeof location === 'string' && location.trim() !== '') {
    const locClean = location.trim().toLowerCase();
    results = results.filter(project => {
      const city = (project.city || '').toLowerCase();
      const addr = (project.address || '').toLowerCase();
      const pin = (project.pincode || '').toLowerCase();
      return city.includes(locClean) || addr.includes(locClean) || pin.includes(locClean);
    });
  }

  // Query search filter (matches name, company_name, notes, subcategory, city, address)
  if (query && typeof query === 'string' && query.trim() !== '') {
    const qClean = query.trim().toLowerCase();
    const qWords = qClean.split(/\s+/).filter(Boolean);
    results = results.filter(project => {
      const searchableText = [
        project.name || '',
        project.company_name || '',
        project.notes || '',
        project.subcategory || '',
        project.city || '',
        project.address || '',
        project.category || '',
        project.project_scale || ''
      ].join(' ').toLowerCase();

      return qWords.every(word => searchableText.includes(word));
    });
  }

  return results;
}

module.exports = {
  ACTIVE_CONSTRUCTION_PROJECTS,
  searchConstructionHarvester
};
